// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagement.Infrastructure;

#nullable disable

namespace SchoolManagement.Api.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241209045711_Migration1")]
    partial class Migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProfessorSubject", b =>
                {
                    b.Property<int>("ProfessorsIdProf")
                        .HasColumnType("int");

                    b.Property<int>("SubjectsIdSub")
                        .HasColumnType("int");

                    b.HasKey("ProfessorsIdProf", "SubjectsIdSub");

                    b.HasIndex("SubjectsIdSub");

                    b.ToTable("ProfessorSubject");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.AuxiliaryMeans", b =>
                {
                    b.Property<int>("IdMean")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMean"));

                    b.Property<int>("Ammount")
                        .HasColumnType("int");

                    b.Property<string>("NameMean")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdMean");

                    b.ToTable("AuxiliaryMeans");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.ClassRoom", b =>
                {
                    b.Property<int>("IdClassR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClassR"));

                    b.Property<bool>("IsAviable")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClassR");

                    b.ToTable("ClassRoom");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Course", b =>
                {
                    b.Property<int>("IdC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdC"));

                    b.HasKey("IdC");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Maintenance", b =>
                {
                    b.Property<int>("IdM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdM"));

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<DateOnly>("MaintenanceDate")
                        .HasColumnType("date");

                    b.HasKey("IdM");

                    b.ToTable("Maintenance");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Professor", b =>
                {
                    b.Property<int>("IdProf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProf"));

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDean")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LaboralExperience")
                        .HasColumnType("int");

                    b.Property<string>("LastNameProf")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("NameProf")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("IdProf");

                    b.ToTable("Professors");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Restriction", b =>
                {
                    b.Property<int>("IdRes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRes"));

                    b.Property<string>("NameRes")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("IdRes");

                    b.ToTable("Restriction");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Secretary", b =>
                {
                    b.Property<int>("IdS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdS"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastNameS")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("NameS")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("SalaryS")
                        .HasColumnType("int");

                    b.HasKey("IdS");

                    b.ToTable("Secretary");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Student", b =>
                {
                    b.Property<int>("IdStud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStud"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("EActivity")
                        .HasColumnType("bit");

                    b.Property<string>("NameStud")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("IdStud");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Subject", b =>
                {
                    b.Property<int>("IdSub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSub"));

                    b.Property<int>("CourseLoad")
                        .HasColumnType("int");

                    b.Property<string>("NameSub")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("StudyProgram")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdSub");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.TechnologicalMeans", b =>
                {
                    b.Property<int>("IdMean")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMean"));

                    b.Property<int>("Ammount")
                        .HasColumnType("int");

                    b.Property<string>("NameMean")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdMean");

                    b.ToTable("TechnologicalMeans");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Relations.StudentSubject", b =>
                {
                    b.Property<int>("IdStud")
                        .HasColumnType("int");

                    b.Property<int>("IdSub")
                        .HasColumnType("int");

                    b.Property<int>("NJAbsents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("IdStud", "IdSub");

                    b.HasIndex("IdSub");

                    b.ToTable("StudentSubject");
                });

            modelBuilder.Entity("ProfessorSubject", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.Professor", null)
                        .WithMany()
                        .HasForeignKey("ProfessorsIdProf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.Domain.Entities.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectsIdSub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagement.Domain.Relations.StudentSubject", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("IdStud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("IdSub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });
#pragma warning restore 612, 618
        }
    }
}
