// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagement.Infrastructure;

#nullable disable

namespace SchoolManagement.Api.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagement.Domain.Entities.AuxiliaryMeans", b =>
                {
                    b.Property<int>("IdMean")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMean"));

                    b.Property<int>("Ammount")
                        .HasColumnType("int");

                    b.Property<string>("NameMean")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdMean");

                    b.ToTable("AuxiliaryMeans");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.ClassRoom", b =>
                {
                    b.Property<int>("IdClassR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClassR"));

                    b.Property<bool>("IsAviable")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClassR");

                    b.ToTable("ClassRoom");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Course", b =>
                {
                    b.Property<int>("IdC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdC"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentIdStud")
                        .HasColumnType("int");

                    b.HasKey("IdC");

                    b.HasIndex("StudentIdStud");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Maintenance", b =>
                {
                    b.Property<int>("IdM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdM"));

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<DateOnly>("MaintenanceDate")
                        .HasColumnType("date");

                    b.HasKey("IdM");

                    b.ToTable("Maintenance");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Professor", b =>
                {
                    b.Property<int>("IdProf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProf"));

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDean")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LaboralExperience")
                        .HasColumnType("int");

                    b.Property<string>("LastNameProf")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("NameProf")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int?>("StudentIdStud")
                        .HasColumnType("int");

                    b.HasKey("IdProf");

                    b.HasIndex("StudentIdStud");

                    b.ToTable("Professor");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Restriction", b =>
                {
                    b.Property<int>("IdRes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRes"));

                    b.Property<string>("NameRes")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("IdRes");

                    b.ToTable("Restrction");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Secretary", b =>
                {
                    b.Property<int>("IdS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdS"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastNameS")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("NameS")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("SalaryS")
                        .HasColumnType("int");

                    b.HasKey("IdS");

                    b.ToTable("Secretary");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Student", b =>
                {
                    b.Property<int>("IdStud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStud"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("EActivity")
                        .HasColumnType("bit");

                    b.Property<int>("IdC")
                        .HasColumnType("int");

                    b.Property<string>("NameStud")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("IdStud");

                    b.HasIndex("IdC");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Subject", b =>
                {
                    b.Property<int>("IdSub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSub"));

                    b.Property<int>("CourseLoad")
                        .HasColumnType("int");

                    b.Property<string>("NameSub")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("StudyProgram")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdSub");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.TechnologicalMeans", b =>
                {
                    b.Property<int>("IdMean")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMean"));

                    b.Property<int>("Ammount")
                        .HasColumnType("int");

                    b.Property<string>("NameMean")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdMean");

                    b.ToTable("TechnologicalMeans");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Relations.ProfessorStudentSubject", b =>
                {
                    b.Property<int>("IdProf")
                        .HasColumnType("int");

                    b.Property<int>("IdStud")
                        .HasColumnType("int");

                    b.Property<int>("IdSub")
                        .HasColumnType("int");

                    b.Property<float>("StudentGrades")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.HasKey("IdProf", "IdStud", "IdSub");

                    b.HasIndex("IdStud", "IdSub");

                    b.ToTable("ProfessorStudentSubject");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Relations.ProfessorSubject", b =>
                {
                    b.Property<int>("IdProfSub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProfSub"));

                    b.Property<int>("IdProf")
                        .HasColumnType("int");

                    b.Property<int>("IdSub")
                        .HasColumnType("int");

                    b.HasKey("IdProfSub");

                    b.HasIndex("IdProf");

                    b.HasIndex("IdSub");

                    b.ToTable("ProfessorSubject");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Relations.StudentSubject", b =>
                {
                    b.Property<int>("IdStud")
                        .HasColumnType("int");

                    b.Property<int>("IdSub")
                        .HasColumnType("int");

                    b.Property<int>("NJAbsents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("IdStud", "IdSub");

                    b.HasIndex("IdSub");

                    b.ToTable("StudentSubject");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Course", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.Student", null)
                        .WithMany("Courses")
                        .HasForeignKey("StudentIdStud");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Professor", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.Student", null)
                        .WithMany("Professors")
                        .HasForeignKey("StudentIdStud");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Student", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("IdC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Relations.ProfessorStudentSubject", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("IdProf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.Domain.Relations.StudentSubject", "StudentSubject")
                        .WithMany()
                        .HasForeignKey("IdStud", "IdSub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("StudentSubject");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Relations.ProfessorSubject", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("IdProf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.Domain.Entities.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("IdSub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Relations.StudentSubject", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("IdStud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("IdSub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Course", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Student", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Professors");
                });
#pragma warning restore 612, 618
        }
    }
}
