// <auto-generated />
using ASP.Net_backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.Net_backend.Migrations
{
    [DbContext(typeof(ProfesorContext))]
    partial class ProfesorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP.Net_backend.Models.Profesor", b =>
                {
                    b.Property<int>("IdP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdP"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("EsDecano")
                        .HasColumnType("bit");

                    b.Property<bool>("FueBorrado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreP")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Salario")
                        .HasColumnType("int");

                    b.Property<string>("TipoContrato")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdP");

                    b.ToTable("Profesor");
                });
#pragma warning restore 612, 618
        }
    }
}
